sudo: false
env:
  global:
  - secure: L4BWhKGMk4PgbEyTCaP7UsoQBRlczpjoSY48tPMP9hNMqsWnXTPRCW8JDrSB/of1H6r3sKgtmwujdnn/IcegTlX26ZfJ+XRk4m/xyENJZ6edpLFx3LQ89MuplQCQy/c72W+45GVxVPmPNWNuvfYXs+6exjbYGWXf+q7MfgGztyP1/MEIRPmNtwIaNsQFLLnWaNLE4246wldiM1QhuC5WT6UmrXeJUEq8a0j5NxFlxs9fr7StmBBZPWvhsQYexNDs6/ycBeeHSbmj98ZNMnKkP+ge6u76uu/mFq2J8OedaIxn7yCrPI7fPyFWmLefEQ/SmA0RCiTrabpcMExRZUxL3y1C6pMA4eVuulh4vmerMZgMY9ngKZyHtPEoL+Itm689RuyUqKNOFjqqYPULbJWjeG9eyC5H+LCA0KnbjgO1jLce1KsjbmzTSITF2Tm0Q5Yccq8/2b/dMn0sbAQEGxRERv+rGO2OrXi6UebkmOE7H8CBQNl/BTZM0HsTKoJ7rVKdtZPMKZbmIzEZsUJ1cOACHibwATZ2tbx1P3hRSZWX/XBPoHmkbjj2iuKjF1B/hp3dbEvi/4uK++fBKY2Ca0qRBcft3cr1ty3mFFo2ZOeI+XZoVSaUZXsbFwevoYr0CW0aAg9e6jfqJlFBUB6q1ZMIXE8hSZ455eRlfY3nqOjbTE4=
  - secure: XMqbQgkKUgnbWd4aJ+3G9MiVx4LFX/RiXQe1r8mPiZnPF2EBpSOSVWy9ls+z5Gk5f3B36sM9oMkRg52SZQnd7+lVn6HUG7U997cUqv1gBm4ckklFTmy2gvT18k5vgUS/GIf8xbLtnPZYUWVxC01d3wVW0vw6PE4WvUVxYk/AYmFts4xTL2OntZtXH+MwBmJsbcpdaYQPo9zqsKBaJWIHxIYrV1vOoBAFdNtKIUXhTlO2hyaXd398ZlnorHi+4JMCEzTJTc9gAtl9/CLVwSjCbK4KFX1pn8xEc1jidtLCmym3lgZCT3gtRV3aFRz55TsFCamppO2g6DcKZWveD/XrcFp/bjZMdZWScve2vHkIGHoo8pNMSgcKOLZblieOPz46njZtcjS6LnJeITts+fpIkluVC/m3PrB2gbvWavxfay8HyZR2CH8LT+pJpHnvV8kGd1NnEN2LZDhCxcxyd8rXWzwM6J3w8RyRlPm7GG3CL5NYVN+s+ykobhKwszncwycSZYhKSdnGGGS0foc4MBOJwOuKvG6EzqSDcGJDUz945J+7lkqyjixmZNL05q8u8ouROV419WXtcSq8d/L3BLzKNPYWNkyJ2aYkd1bpTNvMbGS9zFdI4PNcrs6KaNYWVv888tul4C0PUHhq9ZA0/5ODv5xQfGYjusf+EzA44sfVtL4=
language: node_js
node_js:
- node
install: npm install
script:
- npm test
- gulp
cache:
  directories:
  - node_modules
after_success:
- gulp deploy --user $SFTP_USER --password $SFTP_PASSWORD
