sudo: false
language: node_js
node_js:
- node
install: npm install
script:
- npm test
- npm run build
cache:
  directories:
  - node_modules
after_success:
- test $TRAVIS_BRANCH = "master" && gulp deploy
