env:
  global:
  - 'SFTP_USER=stefanbaust@spltscreen.de'
  - 'SFTP_PASSWORD=[password]'
sudo:          false
language:      node_js
node_js:
  - "node"
install:       npm install
script:
  - npm test
  - gulp
cache:
  directories:
    - node_modules
after_success:
- find . -type f -exec curl -u ${SFTP_USER}:${SFTP_PASSWORD} --ftp-create-dirs -T {} sftp://esm19.siteground.biz/{} \;

